FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d

RUN apt-get -y update
RUN apt-get -y -q install nginx

RUN mkdir -p /var/www/html

ADD ./global.conf /etc/nginx/conf.d/
ADD ./nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx

CMD ["nginx"]
